name: Docker Images CI

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  oracle-18-xe:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and Push
        working-directory: ./oracle-images/OracleDatabase/SingleInstance/dockerfiles
        run: |
          ./buildContainerImage.sh -t dkmoonfruit/oracle:18.4.0-xe -v 18.4.0 -x
          docker push dkmoonfruit/oracle:18.4.0-xe
